export const mockProjectFiles = {
  'index.html': `<main class="shell">
  <header><div><p class="eyebrow">HighLevel workspace</p><h1>Contact pulse</h1><p>Recent relationships and next appointments in one focused view.</p></div><button id="refresh">Refresh</button></header>
  <section class="summary"><article><span>Active contacts</span><strong id="contact-count">-</strong></article><article><span>Appointments</span><strong id="appointment-count">-</strong></article></section>
  <section><div class="section-heading"><h2>Recent contacts</h2><input id="search" placeholder="Search contacts" /></div><div id="contacts"><p class="empty">Loading HighLevel data...</p></div></section>
</main>`,
  'styles.css': `:root{color-scheme:dark;font-family:ui-sans-serif,system-ui;background:#141411;color:#f4f1e8}*{box-sizing:border-box}body{margin:0}.shell{max-width:980px;margin:auto;padding:42px 34px}header,.section-heading{display:flex;align-items:end;justify-content:space-between;gap:24px}.eyebrow{color:#e8bd62;font:600 11px ui-monospace;letter-spacing:.12em;text-transform:uppercase}h1{margin:8px 0;font-size:52px;letter-spacing:-.05em}button,input{border:1px solid #45443e;border-radius:7px;background:#201f1b;color:inherit;padding:10px 14px}button{background:#e8bd62;color:#1b1914;font-weight:700}.summary{display:grid;grid-template-columns:1fr 1fr;margin:42px 0;border-block:1px solid #33322d}.summary article{padding:24px}.summary span{color:#918e84;font-size:13px}.summary strong{display:block;margin-top:8px;font:500 36px ui-monospace}.contact{display:grid;grid-template-columns:1.2fr 1fr auto;gap:20px;padding:15px 2px;border-bottom:1px solid #2e2d29}.contact span,.empty{color:#8e8b82}`,
  'app.js': `const contacts=[{name:'Maya Rivera',email:'maya@northstar.studio'},{name:'Adrian Okafor',email:'adrian@westward.co'},{name:'Linnea Berg',email:'linnea@fieldwork.design'}];function render(items){document.querySelector('#contacts').innerHTML=items.map(contact=>'<article class="contact"><strong>'+contact.name+'</strong><span>'+contact.email+'</span><span>Recent</span></article>').join('');document.querySelector('#contact-count').textContent=String(items.length);document.querySelector('#appointment-count').textContent='0'}document.querySelector('#search').addEventListener('input',event=>render(contacts.filter(contact=>JSON.stringify(contact).toLowerCase().includes(event.target.value.toLowerCase()))));document.querySelector('#refresh').addEventListener('click',()=>render(contacts));render(contacts);`,
} as const
